### ISSUE TITLE
Different step used in query_range when query is triggered from dashboard and panel edit 

### ISSUE THREAD

**Issue by dg-nvm** [VictoriaMetrics/grafana-datasource#151]
When I set time to -30d, dashboard refresh makes a query with step: 3600 (1h), when I go to one of the panels and do refresh, new query is having step 1800 (30m), which is aligned with what panel ui presents. It's the same for other settings like -3h will set 20s for dashboard query and 10s for edit query.

Datasource version 0.8.0

**Comment by hagen1778** [comment]
@dg-nvm @Loori-R I believe Grafana automatically adjusts the `step` param according to the panel "resolution" (amount of pixels available for plotting on your display). 
It is likely in the first case, when you observe many panels on the page, you have step of 1h because you have two columns on the screen. Hence, each panel has 50% of your resolution.
When you go to a specific panel (by pressing View/Edit), the panel gets 100% of your screen width and Grafana increases graph resolution by decreasing step param by x2.

@Loori-R @dg-nvm could you please verify this assumption? Can you check if other Grafana datasources like Prometheus behave differently?

**Comment by dg-nvm** [comment]
@hagen1778 it does seem right what you said, resizing panel is indeed doing different steps. The problem in this case is that we use `Single Stat` panel that will simply return different number per different step. In this case the size does not matter because only number is displayed. I was experimenting with max_lookback to limit the problems of step changes but it didn't bring the results I expected. Will have to start different Grafana to also check Prometheus

**Comment by dg-nvm** [comment]
Yep Prometheus datasource do the same, will have to check how to limit the problem for discrete metrics when lookback can introduce big difference. I experimented with max_lookback set to scrape interval but it didn't produce the results I wanted. When migrating from databases like Influx that works more or less like standard SQL databases, just with metrics, to Prometheus-like world, these things can happen :)

**Comment by hagen1778** [comment]
>The problem in this case is that we use Single Stat panel that will simply return different number per different step

Could you please show the query you use for this panel?

**Comment by dg-nvm** [comment]
@hagen1778 Setting max data points to 1 and adding static [1d] to sum_over_time helped, now step is static value

**Comment by hagen1778** [comment]
Thanks for update!
