### ISSUE TITLE
vmui link doesn't work 

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/grafana-datasource#171]
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/24344673/88d67887-d6f5-4175-b5a1-bb54637357e0)

https://play-grafana.victoriametrics.com/d/LzldHAVnz_vm/victoriametrics-vmalert-vm?orgId=1&var-ds=P38648FE0F8C5BEA2&var-job=All&var-instance=All&var-group=All&var-topk=5&var-adhoc=job%7C%3D%7Cmonitoring%2Fprometheus-benchmark-vmalert&editPanel=23

**Comment by tiny-pangolin** [comment]
This doesn't appear to be a bug with the datasource but a bug with how it deployed in in play. The Victoriametrics data source is configured to use the internal kubernetes URL but doesn't have it VMUI URL option set in the data source so it defaults to `{{ datasource_url}}/vmui` I'll work with the team to get fixed in playground.

**Comment by tiny-pangolin** [comment]
the link above appears to be behaving correct. It was fixed by defining `vmuiUrl` in json data of the datasource provisioning config in Grafana.
